- project:
    check:
      jobs:
        - openstack-tox-lower-constraints
            required-projects:
              - openstack/neutron
    gate:
      jobs:
        - openstack-tox-lower-constraints
            required-projects:
              - openstack/neutron